server:
  port : 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: root1234

    hikari:
      pool-name: HikariCP
      maximum-pool-size: 5
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 1800000
      leak-detection-threshold: 0
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:prashantbhandari191111989_prashantbhandari191111989_prashantbhandari19111989}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}


#oauth configurations
spring.security.oauth2.client.registration :
#  THIS IS THE CALLBACK URL FOR AUTHORIZATION FOR ANY OAUTH2 - http://localhost:8082/login/oauth2/code/{google or gitHub}
  google:
    client-id: ${GOOGLE_CLIENT_ID:test-client-id}
    client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
    scope:
      - email
      - profile
      - openid
  github:
    client-id: ${GITHUB_CLIENT_ID:test-client-id}
    client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
    scope:
      - user:email
      - read:profile

app:
  cors:
    front-end-url: http://localhost:5173,
  auth:
    frontend:
      success-redirect: http://localhost:5173/auth/success
      failure-redirect: http://localhost:5173/auth/failure